spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/botdemo?characterEncoding=UTF-8
    username: root
    password: 12345678
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
telegram:
  bot:
    username: ${TELEGRAM_USERNAME}
    token: ${TELEGRAM_TOKEN}
management:
  endpoints:
    web:
      exposure:
        include: '*'
